
DROP TABLE USER;
CREATE TABLE USER(
	IP TEXT PRIMARY key not null,
	FOREIGN KEY (IP) REFERENCES LIKES(IP)
);

DROP TABLE LIKES;
CREATE TABLE LIKES(
	ISBN int not null,
	IP text not null,
	LIKES INT not null,
	DISLIKES INT not null,
	FOREIGN KEY (ISBN) REFERENCES BOOKS(ISBN),
	FOREIGN KEY (IP) REFERENCES USER(IP)
);

DROP TABLE BOOKS;
CREATE TABLE BOOKS(
	ISBN INT PRIMARY key not null,
	TITULO TEXT,
	SINOPSE TEXT,
	FOREIGN KEY (ISBN) REFERENCES LIKES(ISBN)
);